version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: spring-template-container
    restart: always
    environment:
      POSTGRES_USER: davi_admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spring-template
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: